name: Push to DigitalOcean App Platform
on:
    push:
        branches:
            - main
jobs:
    push:
        environment: prod
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: 'recursive'
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: Install backend dependencies
              run: npm install
            - name: Install frontend dependencies
              run: cd frontend && npm install
            - name: build frontend
              run: npm run build
              env:
                NODE_ENV: prod
                VUE_APP_ENV_GOOGLE_CALLBACK: ${{ vars.GOOGLE_CALLBACK }}
                VUE_APP_ENV_GOOGLE_CLIENT_ID: ${{ vars.GOOGLE_CLIENT_ID }}
            - name: DigitalOcean App Platform deployment
              uses: digitalocean/app_action@v1.1.5
              with:
                app_name: ${{ vars.APP_NAME }}
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            